version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/tableau_creation.sql:/docker-entrypoint-initdb.d/tableau_creation.sql
    networks:
      - my-network


  frontend:
    build:
      context: ./front-app
    ports:
      - "3000:3000"
    networks:
      - my-network

  backend:
    build:
      context: ./REST-API-DTO
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET = ${JWT_SECRET}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
